# Kill it xd
set(CMAKE_MODULE_PATH ${ORIGINAL_CMAKE_MODULE_PATH})
find_package(OpenSSL)
set(CMAKE_MODULE_PATH ${OWN_CMAKE_MODULE_PATH})

set(OPENSSL_CRYPTO_LIBRARIES)
set(OPENSSL_INCLUDE_DIRS)
set_extra_dirs_lib(OPENSSL openssl)

if(OPENSSL_FOUND)
  set(OPENSSL_CRYPTO_LIBRARIES ${OPENSSL_CRYPTO_LIBRARY})
  set(OPENSSL_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})

  if(TARGET_OS STREQUAL "windows")
    set(OPENSSL_COPY_FILES "${EXTRA_OPENSSL_LIBDIR}/libeay32.dll" "${EXTRA_OPENSSL_LIBDIR}/ssleay32.dll")
  endif()
endif()
