set_extra_dirs_lib(CEGUI cegui)
####################################### CEGUI
find_library(OWN_CEGUIBASE_LIB
  NAMES "CEGUIBase-0"
  HINTS ${HINTS_CEGUI_LIBDIR} ${CEGUI_CONFIG_LIBRARY_PATH}
  PATHS ${PATHS_CEGUI_LIBDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
set_extra_dirs_include(CEGUI cegui "${OWN_CEGUIBASE_LIB}")
find_path(OWN_CEGUI_INCLUDEDIR
  NAMES "CEGUI/GUIContext.h"
  HINTS ${HINTS_CEGUI_INCLUDEDIR} ${CEGUI_CONFIG_INCLUDE_DIR}
  PATHS ${PATHS_CEGUI_INCLUDEDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
find_library(OWN_CEGUIRENDER_LIB
  NAMES "CEGUIOpenGLRenderer-0"
  HINTS ${HINTS_CEGUI_LIBDIR} ${CEGUI_CONFIG_LIBRARY_PATH}
  PATHS ${PATHS_CEGUI_LIBDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)

#######################################
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CEGUI DEFAULT_MSG OWN_CEGUIBASE_LIB OWN_CEGUI_INCLUDEDIR)
mark_as_advanced(OWN_CEGUIBASE_LIB OWN_CEGUI_INCLUDEDIR)

#######################################
set(CEGUI_LIBRARIES ${OWN_CEGUIBASE_LIB} ${OWN_CEGUIRENDER_LIB})
set(CEGUI_INCLUDE_DIRS ${OWN_CEGUI_INCLUDEDIR})
  
if(TARGET_OS AND TARGET_OS STREQUAL "windows")
  set(CEGUI_COPY_FILES "${EXTRA_CEGUI_LIBDIR}/CEGUIBase-0.dll" "${EXTRA_CEGUI_LIBDIR}/CEGUIOpenGLRenderer-0.dll")
else()
  set(CEGUI_COPY_FILES)
endif()