name: All OS
on:
  push:
    branches: 
      - master
    tags:
      - 'v*.*.*'
jobs:
  build_ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: |
          sudo apt-get update -y
          sudo apt-get install cmake libcurl4-openssl-dev libfreetype6-dev libglew-dev libogg-dev libopus-dev libopusfile-dev libpnglite-dev libsdl2-dev libwavpack-dev python -y
          git submodule update --init
          
      - name: Build Mmo-Clinet Cmake Release mode
        run: |
          mkdir -p release
          cd release
          cmake ..
          make everything
          ./mmoteeworlds shutdown
          cd ..
          
      - name: Bundle Zip-Package
        run: |
          zip test_ubuntu.zip release/mmoteeworlds
          
      - name: Deploy Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Ubuntu-latest
          files: |
            test_ubuntu.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    name: Build Windows x86
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: |
            git submodule update --init
            mkdir -p release
            cd release
            cmake -G "Visual Studio 16 2019" ..
            
      - name: Build
        run: |
            cmake --build release --config Release --target everything
            mv release\Release\mmoteeworlds.exe release
            
      - name: Bundle Zip-Package
        run: |
          jar -cMf mmoclient_windows32.zip -C release\Release .\release
          jar -uf mmoclient_windows32.zip release\data release\freetype.dll release\libcurl.dll release\libogg.dll
          jar -uf mmoclient_windows32.zip release\libopus.dll release\libopusfile.dll release\libwinpthread-1.dll

      - name: Deploy Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Windows-latest
          files: |
            mmoclient_windows32.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
