name: All OS
on:
  push:
    branches: 
      - master
    tags:
      - 'v*.*.*'
jobs:
  build_ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: |
          sudo apt-get update -y
          sudo apt-get install cmake libcurl4-openssl-dev libfreetype6-dev libglew-dev libogg-dev libopus-dev libopusfile-dev libpnglite-dev libsdl2-dev libwavpack-dev python -y
          git submodule update --init
          
      - name: Build Cmake Mmo-Clinet
        run: |
          mkdir -p mmoclient
          cd mmoclient
          cmake ..
          make everything
          ./mmoteeworlds shutdown
          cd ..
          
      - name: Bundle Tar-gz Package
        run: |
          mv storage.cfg mmoclient/
          tar -cvzf mmoclient_linux-x86_64.tar.gz mmoclient/data mmoclient/mmoteeworlds mmoclient/storage.cfg

      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Ubuntu-latest
          files: |
            mmoclient_linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    name: Build Windows x86
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: |
            git submodule update --init
            mkdir -p mmoclient
            cd mmoclient
            cmake -G "Visual Studio 16 2019" ..
            
      - name: Build
        run: |
            cmake --build mmoclient --config Release --target everything
            move mmoclient\Release\mmoteeworlds.exe  mmoclient\
            move storage.cfg  mmoclient\
            
      - name: Bundle Zip-Package
        run: |
          jar -cMf mmoclient_windows32.zip mmoclient\mmoteeworlds.exe mmoclient\storage.cfg
          jar -uf mmoclient_windows32.zip mmoclient\data mmoclient\freetype.dll mmoclient\libcurl.dll mmoclient\libogg.dll
          jar -uf mmoclient_windows32.zip mmoclient\libopus.dll mmoclient\libopusfile.dll mmoclient\libwinpthread-1.dll mmoclient\SDL2.dll

      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Windows-latest
          files: |
            mmoclient_windows32.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_mac:
    name: Build MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: |
          brew install freetype sdl2 curl
          git submodule update --init
      - name: Build Bam
        run: |
          git clone https://github.com/matricks/bam.git ~/bam
          cd ~/bam/
          git reset --hard f012dd9a3e38295b8a45af5a101d29573381f169
          ./make_unix.sh
      - name: Build Release
        run: |
          ~/bam/bam conf=release all
      - name: Bundle Zip-Package
        run: |
          zip mmoclient_macos.zip build/x86_64/release/mmoteeworlds
      - name: Deploy Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: MacOS-latest
          files: |
            mmoclient_macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
